profiler:
  registry: registry.internal.tensor.works
  repository: sps-dave
  image: pod-profiler-gatherer
  version: 0.0.0-devel
  resources:
    replicas: 1
    requests:
      cpu: 500m 
      memory: 50Mi  
    limits:
      cpu: 500m
      memory: 50Mi
http:
  port: 80  
results:
  path: ./results
frontend:
  registry: registry.internal.tensor.works
  repository: sps-dave
  image: pod-profiler-frontend
  version: 0.0.0-devel
  resources:
    replicas: 1
    requests:
      cpu: 500m 
      memory: 50Mi
    limits:
      cpu: 500m
      memory: 50Mi