# pod-profiler-gatherer
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-profiler-gatherer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pod-profiler-gatherer
data:
  config-kubernetes.json: |
    {
      "namespace": {{ .Release.Namespace | quote }},
      "httpport": {{ .Values.http.port }},
      "resultspath": {{ .Values.results.path | quote }},
      "podlabels": [
        "sps-api",
        "sps-cloud-keeper",
        "sps-coturn",
        "sps-dashboard",
        "sps-frontend-demo",
        "sps-metric-service",
        "sps-operator",
        "sps-instance-manager-demo",
        "sps-auth-demo",
        "sps-signalling-server-demo"
      ]
    }
#EOF

---

# pod-profiler-frontend

apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-profiler-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pod-profiler-frontend
data:
  nginx.conf: |
    events {}
    http {

      include  /etc/nginx/mime.types;
      
      server {

        listen 80 default_server;
        listen [::]:80 default_server;

        rewrite ^([^.]*[^/])$ $1/ redirect;
        rewrite ^/[0-9a-z-]+(/|$)(.*) /$2 last;
        root /www;

        location /results {
          add_header Access-Control-Allow-Origin *;
          autoindex on;
        }
        
      }
    }
# EOF