apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-profiler
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pod-profiler
data:
  config-kubernetes.json: |
    {
      "namespace": {{ .Release.Namespace | quote }},
      "httpport": {{ .Values.http.port }},
      "resultspath": {{ .Values.results.path | quote }},
      "deployments": [
        "sps-operator"
      ]
    }
