apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-profiler
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pod-profiler
data:
  config-kubernetes.json: |
    {
      "namespace": {{ .Release.Namespace | quote }},
      "httpport": {{ .Values.http.port }},
      "resultspath": {{ .Values.results.path | quote }},
      "podlabels": [
        "sps-api",
        "sps-cloud-keeper",
        "sps-coturn",
        "sps-dashboard",
        "sps-frontend-demo",
        "sps-metric-service",
        "sps-operator",
        "sps-instance-manager-demo",
        "sps-auth-demo",
        "sps-signalling-server-demo"
      ]
    }
