apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-profiler
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pod-profiler
data:
  config-kubernetes.yaml: |
    namespace: {{ .Release.Namespace }}
