apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-profiler-results
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
