# Profiler role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-profiler
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-profiler
subjects:
  - kind: ServiceAccount
    name: pod-profiler
    namespace: {{ .Release.Namespace }}
