# Dashboard Service
apiVersion: v1
kind: Service
metadata:
  name: pod-profiler-frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: pod-profiler-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80